apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: default
type: Opaque
stringData:
  # Kubernetes handles the encoding for us upon cluster injection
  DATABASE_CONNECTION: "Host=prod-db-cluster;Database=Catalog;Username=roy;Password=SuperSecretPassword123"